CREATE TYPE "public"."CaseCategory" AS ENUM (
    'ESTRATEGIA',
    'OPERACIONES',
    'FINANZAS',
    'MARKETING',
    'IMPACTO_SOCIAL'
);


ALTER TYPE "public"."CaseCategory" OWNER TO "postgres";


COMMENT ON TYPE "public"."CaseCategory" IS 'Area de negocio que aborda el caso de estudio';


CREATE TYPE "public"."CaseDifficulty" AS ENUM (
    'FACIL',
    'MEDIO',
    'DIFICIL',
    'EXPERTO'
);


ALTER TYPE "public"."CaseDifficulty" OWNER TO "postgres";


COMMENT ON TYPE "public"."CaseDifficulty" IS 'Nivel de dificultad del caso de estudio';


CREATE TYPE "public"."CaseResourceKind" AS ENUM (
    'APUNTE',
    'DATASET',
    'MASTERCLASS'
);


ALTER TYPE "public"."CaseResourceKind" OWNER TO "postgres";


COMMENT ON TYPE "public"."CaseResourceKind" IS 'Tipo de recurso complementario asociado a un caso de estudio';


CREATE TABLE IF NOT EXISTS "public"."CaseStudies" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "company" "text",
    "company_logo_url" "text",
    "category" "public"."CaseCategory" NOT NULL,
    "difficulty" "public"."CaseDifficulty",
    "duration_minutes" integer,
    "case_type" "text",
    "summary" "text",
    "problem_statement" "text",
    "document_url" "text",
    "document_name" "text",
    "document_size_bytes" bigint,
    "published_date" "date",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."CaseStudies" OWNER TO "postgres";


COMMENT ON TABLE "public"."CaseStudies" IS 'Biblioteca de casos de estudio del material de estudio';


COMMENT ON COLUMN "public"."CaseStudies"."document_url" IS 'Path relativo dentro del bucket documents, o URL absoluta si el archivo es externo';


ALTER TABLE "public"."CaseStudies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."CaseStudies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."CaseStudies"
    ADD CONSTRAINT "CaseStudies_pkey" PRIMARY KEY ("id");


CREATE TABLE IF NOT EXISTS "public"."CaseStudyResources" (
    "id" bigint NOT NULL,
    "case_study_id" bigint NOT NULL,
    "kind" "public"."CaseResourceKind" NOT NULL,
    "title" "text" NOT NULL,
    "link" "text",
    "document_url" "text",
    "position" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."CaseStudyResources" OWNER TO "postgres";


COMMENT ON TABLE "public"."CaseStudyResources" IS 'Recursos complementarios (apuntes, datasets, masterclasses) asociados a un caso de estudio';


ALTER TABLE "public"."CaseStudyResources" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."CaseStudyResources_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."CaseStudyResources"
    ADD CONSTRAINT "CaseStudyResources_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."CaseStudyResources"
    ADD CONSTRAINT "CaseStudyResources_case_study_id_fkey" FOREIGN KEY ("case_study_id")
    REFERENCES "public"."CaseStudies"("id") ON DELETE CASCADE;


CREATE INDEX "CaseStudyResources_case_study_id_idx" ON "public"."CaseStudyResources" USING "btree" ("case_study_id");


CREATE POLICY "Enable full access for authenticated users" ON "public"."CaseStudies" TO "authenticated" USING (true) WITH CHECK (true);


CREATE POLICY "Enable read access for all users" ON "public"."CaseStudies" FOR SELECT USING (true);


ALTER TABLE "public"."CaseStudies" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Enable full access for authenticated users" ON "public"."CaseStudyResources" TO "authenticated" USING (true) WITH CHECK (true);


CREATE POLICY "Enable read access for all users" ON "public"."CaseStudyResources" FOR SELECT USING (true);


ALTER TABLE "public"."CaseStudyResources" ENABLE ROW LEVEL SECURITY;


GRANT ALL ON TABLE "public"."CaseStudies" TO "anon";
GRANT ALL ON TABLE "public"."CaseStudies" TO "authenticated";
GRANT ALL ON TABLE "public"."CaseStudies" TO "service_role";


GRANT ALL ON SEQUENCE "public"."CaseStudies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."CaseStudies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."CaseStudies_id_seq" TO "service_role";


GRANT ALL ON TABLE "public"."CaseStudyResources" TO "anon";
GRANT ALL ON TABLE "public"."CaseStudyResources" TO "authenticated";
GRANT ALL ON TABLE "public"."CaseStudyResources" TO "service_role";


GRANT ALL ON SEQUENCE "public"."CaseStudyResources_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."CaseStudyResources_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."CaseStudyResources_id_seq" TO "service_role";


-- Bucket `documents`: guarda los PDF de los casos y los archivos de sus recursos.
-- Se crea aqui (y no solo en supabase/config.toml, que aplica unicamente al stack local)
-- para que `supabase db push` lo replique en el proyecto de la nube sin pasos manuales.
INSERT INTO "storage"."buckets" ("id", "name", "public", "file_size_limit", "allowed_mime_types")
VALUES (
    'documents',
    'documents',
    true,
    52428800,
    ARRAY[
        'application/pdf',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-excel'
    ]
)
ON CONFLICT ("id") DO NOTHING;


-- Mismas politicas que el bucket `images`: lectura publica, escritura solo autenticados.
CREATE POLICY "Give all users read access to the documents bucket"
    ON "storage"."objects"
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (("bucket_id" = 'documents'::"text"));


CREATE POLICY "Give authenticated users insert access to documents"
    ON "storage"."objects"
    AS PERMISSIVE
    FOR INSERT
    TO authenticated
    WITH CHECK ((("bucket_id" = 'documents'::"text") AND ("auth"."role"() = 'authenticated'::"text")));


CREATE POLICY "Give authenticated users update access to documents"
    ON "storage"."objects"
    AS PERMISSIVE
    FOR UPDATE
    TO authenticated
    USING ((("bucket_id" = 'documents'::"text") AND ("auth"."role"() = 'authenticated'::"text")));


CREATE POLICY "Give authenticated users delete access to documents"
    ON "storage"."objects"
    AS PERMISSIVE
    FOR DELETE
    TO authenticated
    USING ((("bucket_id" = 'documents'::"text") AND ("auth"."role"() = 'authenticated'::"text")));
