

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."ClubCoordination" AS ENUM (
    'DIRECTORS',
    'COMMS_MKT',
    'SOC_CONSULT',
    'PEOPLE_MGMT',
    'LEARNING_DEV',
    'EXTERNAL_REL',
    'IT',
    'FINANCE'
);


ALTER TYPE "public"."ClubCoordination" OWNER TO "postgres";


COMMENT ON TYPE "public"."ClubCoordination" IS 'Representa los puestos/coordinaciones actuales';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Events" (
    "id" bigint NOT NULL,
    "title" character varying NOT NULL,
    "subtitle" character varying NOT NULL,
    "description" "text",
    "date" timestamp with time zone,
    "image_url" "text",
    "location" "text",
    "link" "text"
);


ALTER TABLE "public"."Events" OWNER TO "postgres";


ALTER TABLE "public"."Events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."News" (
    "id" bigint NOT NULL,
    "image_url" character varying,
    "type" character varying,
    "title" character varying,
    "subtitle" character varying,
    "author" character varying,
    "published_date" timestamp with time zone,
    "content" "text",
    "link" character varying
);


ALTER TABLE "public"."News" OWNER TO "postgres";


ALTER TABLE "public"."News" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."News_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Projects" (
    "id" bigint NOT NULL,
    "title" character varying,
    "subtitle" character varying,
    "description" character varying,
    "image_url" character varying,
    "link" character varying,
    "link_text" character varying
);


ALTER TABLE "public"."Projects" OWNER TO "postgres";


ALTER TABLE "public"."Projects" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Projects_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Team" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "coordination" "public"."ClubCoordination" NOT NULL
);


ALTER TABLE "public"."Team" OWNER TO "postgres";


COMMENT ON TABLE "public"."Team" IS 'Tabla para los datos de los integrantes del equipo de Pontem';



COMMENT ON COLUMN "public"."Team"."coordination" IS 'Coordinación a la que pertenece el miembro del equipo';



CREATE TABLE IF NOT EXISTS "public"."TeamCoordination" (
    "coordination" "public"."ClubCoordination" NOT NULL,
    "image_url" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."TeamCoordination" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."Users" (
    "id" bigint NOT NULL,
    "username" character varying NOT NULL,
    "password" character varying
);


ALTER TABLE "public"."Users" OWNER TO "postgres";


ALTER TABLE "public"."Users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Users_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Team" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."team_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."Events"
    ADD CONSTRAINT "Events_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."Events"
    ADD CONSTRAINT "Events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."News"
    ADD CONSTRAINT "News_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Projects"
    ADD CONSTRAINT "Projects_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."TeamCoordination"
    ADD CONSTRAINT "TeamCoordination_pkey" PRIMARY KEY ("coordination");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."Team"
    ADD CONSTRAINT "team_pkey" PRIMARY KEY ("id");



CREATE POLICY "Enable full access for authenticated users" ON "public"."Events" TO "authenticated" USING (true);



CREATE POLICY "Enable full access for authenticated users" ON "public"."Projects" TO "authenticated" USING (true);



CREATE POLICY "Enable full access for authenticated users" ON "public"."Team" TO "authenticated" USING (true);



CREATE POLICY "Enable full access for authenticated users" ON "public"."TeamCoordination" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Enable full access for authenticated users only" ON "public"."News" TO "authenticated" USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."Events" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."News" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."Projects" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."Team" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."TeamCoordination" FOR SELECT USING (true);



ALTER TABLE "public"."Events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."News" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Projects" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Team" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."TeamCoordination" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";












































































































































































































GRANT ALL ON TABLE "public"."Events" TO "anon";
GRANT ALL ON TABLE "public"."Events" TO "authenticated";
GRANT ALL ON TABLE "public"."Events" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."News" TO "anon";
GRANT ALL ON TABLE "public"."News" TO "authenticated";
GRANT ALL ON TABLE "public"."News" TO "service_role";



GRANT ALL ON SEQUENCE "public"."News_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."News_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."News_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Projects" TO "anon";
GRANT ALL ON TABLE "public"."Projects" TO "authenticated";
GRANT ALL ON TABLE "public"."Projects" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Projects_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Projects_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Projects_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Team" TO "anon";
GRANT ALL ON TABLE "public"."Team" TO "authenticated";
GRANT ALL ON TABLE "public"."Team" TO "service_role";



GRANT ALL ON TABLE "public"."TeamCoordination" TO "anon";
GRANT ALL ON TABLE "public"."TeamCoordination" TO "authenticated";
GRANT ALL ON TABLE "public"."TeamCoordination" TO "service_role";



GRANT ALL ON TABLE "public"."Users" TO "anon";
GRANT ALL ON TABLE "public"."Users" TO "authenticated";
GRANT ALL ON TABLE "public"."Users" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Users_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."team_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."team_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."team_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























drop extension if exists "pg_net";


  create policy "Give all users read access to the bucket 1ffg0oo_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'images'::text));



  create policy "Give authenticated users full access 1ffg0oo_1"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'images'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Give authenticated users full access 1ffg0oo_2"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'images'::text) AND (auth.role() = 'authenticated'::text)));



  create policy "Give authenticated users full access 1ffg0oo_3"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'images'::text) AND (auth.role() = 'authenticated'::text)));



