CREATE TABLE IF NOT EXISTS "public"."HeroSlides" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "subtitle" "text",
    "button_text" "text",
    "image_url" "text",
    "link" "text",
    "position" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."HeroSlides" OWNER TO "postgres";


ALTER TABLE "public"."HeroSlides" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."HeroSlides_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."HeroSlides"
    ADD CONSTRAINT "HeroSlides_pkey" PRIMARY KEY ("id");



CREATE POLICY "Enable full access for authenticated users" ON "public"."HeroSlides" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."HeroSlides" FOR SELECT USING (true);



ALTER TABLE "public"."HeroSlides" ENABLE ROW LEVEL SECURITY;



GRANT ALL ON TABLE "public"."HeroSlides" TO "anon";
GRANT ALL ON TABLE "public"."HeroSlides" TO "authenticated";
GRANT ALL ON TABLE "public"."HeroSlides" TO "service_role";



GRANT ALL ON SEQUENCE "public"."HeroSlides_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."HeroSlides_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."HeroSlides_id_seq" TO "service_role";



INSERT INTO "public"."HeroSlides" ("title", "subtitle", "button_text", "image_url", "link", "position") VALUES
    ('Únete al Equipo', 'Postula y sé parte de Pontem Consulting Club', 'Postula', '/Equipo2024.jpeg', 'https://forms.office.com/r/shGF6Q1Zdd', 1),
    ('Pontem Consulting Club', 'Conectamos estudiantes con el mundo de la consultoría y generamos impacto social.', 'Ver eventos', '/BTGDay.jpeg', '/eventos', 2),
    ('Proyectos de consultoría social', 'Participa en proyectos que generan impacto en fundaciones y ONGs.', 'Conoce más', '/BienvenidaConsultores.jpg', '/consultoria-social', 3),
    ('Conoce nuestro Club', 'Descubre la historia de Pontem y conoce a los miembros del equipo.', 'Nosotros', '/Jornada_Pontem.JPG', '/nosotros', 4);
