-- Inscripciones a eventos.
--
-- Referencias al documento de requisitos: FR-18 a FR-23 y FR-32 a FR-34.
--
-- Los eventos existentes quedan exactamente como estan: `registration_mode`
-- nace en 'none', asi que /eventos no cambia hasta que alguien active la
-- inscripcion en un evento concreto.

-- ============================================================
-- Enums
-- ============================================================

create type public.registration_status as enum ('registered', 'cancelled', 'waitlisted');

-- FR-32: tres modos y no un booleano, porque el club hace tres cosas distintas.
--   none         evento informativo, no se inscribe nadie
--   members_only actividad interna, solo cuentas con sesion
--   open         actividad de cara afuera, miembros e invitados
create type public.registration_mode as enum ('none', 'members_only', 'open');

-- ============================================================
-- Columnas nuevas en Events  (FR-32, FR-34)
-- ============================================================

alter table public."Events"
    add column registration_mode public.registration_mode not null default 'none',
    add column capacity int,
    add column registration_open boolean not null default true;

comment on column public."Events".capacity is
    'Cupo maximo. Null = sin limite (FR-20).';
comment on column public."Events".registration_open is
    'Interruptor manual para cerrar o reabrir antes de la fecha (FR-34).';

alter table public."Events"
    add constraint events_capacity_positive check (capacity is null or capacity > 0);

-- ============================================================
-- event_registrations  (FR-18, FR-33)
-- ============================================================

create table public.event_registrations (
    id            bigint generated by default as identity primary key,
    event_id      bigint not null references public."Events" (id) on delete cascade,
    -- Null cuando es invitado: no tiene cuenta ni perfil (FR-33).
    profile_id    uuid references public.profiles (id) on delete cascade,
    guest_name    text,
    guest_email   text,
    status        public.registration_status not null default 'registered',
    attended      boolean not null default false,
    registered_at timestamptz not null default now(),

    -- O es de una persona con cuenta, o de un invitado. Nunca las dos, nunca
    -- ninguna.
    constraint event_registrations_member_xor_guest
        check (num_nonnulls(profile_id, guest_email) = 1),

    -- Si es de invitado, el nombre es obligatorio: una lista de asistencia con
    -- solo correos no le sirve a nadie en la puerta.
    constraint event_registrations_guest_needs_name
        check (profile_id is not null or nullif(trim(coalesce(guest_name, '')), '') is not null)
);

-- Dos indices parciales y no un unique normal: con `profile_id` en null, un
-- unique(event_id, profile_id) deja de restringir nada y el mismo correo de
-- invitado podria inscribirse infinitas veces.
create unique index event_registrations_one_per_member
    on public.event_registrations (event_id, profile_id)
    where profile_id is not null;

create unique index event_registrations_one_per_guest
    on public.event_registrations (event_id, lower(guest_email))
    where guest_email is not null;

create index event_registrations_by_event on public.event_registrations (event_id);
create index event_registrations_by_profile on public.event_registrations (profile_id);

-- ============================================================
-- RLS  (FR-21)
-- ============================================================

alter table public.event_registrations enable row level security;

-- Cada quien ve lo suyo.
create policy "registrations_select_own" on public.event_registrations
    for select to authenticated
    using (profile_id = auth.uid());

-- Editores y administracion ven la lista completa para organizar (EDI-2).
create policy "registrations_select_staff" on public.event_registrations
    for select to authenticated
    using (public.can_edit_content());

-- Inscribirse: solo a nombre propio, solo en eventos futuros, abiertos y con un
-- modo que admita inscripcion. El evento manda, no el cliente.
create policy "registrations_insert_own" on public.event_registrations
    for insert to authenticated
    with check (
        profile_id = auth.uid()
        and exists (
            select 1 from public."Events" e
             where e.id = event_id
               and e.registration_mode in ('members_only', 'open')
               and e.registration_open
               and (e.date is null or e.date > now())
        )
    );

-- Cancelar lo propio (FR-19). El insert ya limito a que la fila sea suya.
create policy "registrations_update_own" on public.event_registrations
    for update to authenticated
    using (profile_id = auth.uid())
    with check (profile_id = auth.uid());

-- Marcar asistencia (FR-21).
create policy "registrations_update_staff" on public.event_registrations
    for all to authenticated
    using (public.can_edit_content())
    with check (public.can_edit_content());

-- El anonimo no recibe policy de insert a proposito (FR-33): las inscripciones
-- de invitados entran por una ruta del servidor que valida y limita el ritmo.
-- Una policy de insert para `anon` seria un INSERT sin autenticar sobre una
-- tabla publica, defendido solo por una subconsulta.

grant select, insert, update on public.event_registrations to authenticated;
grant all on public.event_registrations to service_role;
grant usage, select on sequence public.event_registrations_id_seq to authenticated, service_role;

-- ============================================================
-- Cupo  (FR-20)
-- ============================================================

-- El cupo se comprueba en un trigger y no en la ruta: dos personas pulsando a la
-- vez pasarian las dos por un `select count(*)` en el servidor.
create function public.event_registrations_enforce_capacity()
returns trigger
language plpgsql
as $$
declare
    limite  int;
    tomados int;
begin
    if new.status <> 'registered' then
        return new;
    end if;

    select capacity into limite from public."Events" where id = new.event_id;

    if limite is null then
        return new;
    end if;

    -- Bloquea la fila del evento para que dos inscripciones simultaneas se
    -- serialicen en vez de pasar las dos.
    perform 1 from public."Events" where id = new.event_id for update;

    select count(*) into tomados
      from public.event_registrations
     where event_id = new.event_id
       and status = 'registered'
       and id is distinct from new.id;

    if tomados >= limite then
        raise exception 'Este evento ya no tiene cupos disponibles'
            using errcode = 'check_violation';
    end if;

    return new;
end;
$$;

create trigger event_registrations_enforce_capacity
    before insert or update on public.event_registrations
    for each row execute function public.event_registrations_enforce_capacity();
